config/routes.rb
Rails.application.routes.draw do
  # root "facts#index"
  root "login#index"

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"

  get "/admin" => "admin/interface#index", :as => :admin_interface
  resources :facts, controller: "admin/facts", only: [:new, :create, :show, :edit, :update, :destroy]
  resources :species, controller: "admin/species", only: [:new, :create, :show, :edit, :update, :destroy]

  namespace :api do
    scope "(:locale)", locale: /en|da/ do
      get "fact", to: "facts#index"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fact.rb
class Fact < ApplicationRecord
  extend Mobility

  belongs_to :species
  has_many :photos, through: :species

  translates :fact, column_suffix: "_i18n"

  scope :ordered, -> { order(id: :desc) }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :species
  has_one_attached :blob

  def blob_width
    blob.metadata["width"]
  end

  def blob_height
    blob.metadata["height"]
  end
end

app/models/species.rb
class Species < ApplicationRecord
  extend Mobility

  translates :common_name, column_suffix: "_i18n"

  has_many_attached :photos

  has_many :photos
  has_many :facts

  # def photo
  #   photos.first
  # end
end

app/controllers/admin/facts_controller.rb
class Admin::FactsController < SecuredController
  def new
    @fact = Fact.new
    @fact.species = Species.find(params[:species_id])
  end

  def create
    @fact = Fact.new(fact_params)

    if @fact.save
      respond_to do |format|
        format.html { redirect_to species_path(@fact.species), notice: "Fact was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @fact = Fact.find(params[:id])
  end

  def update
    @fact = Fact.find(params[:id])

    if @fact.update(fact_params)
      redirect_to species_path(@fact.species), notice: "Fact was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @fact = Fact.find(params[:id])
    @fact.destroy

    respond_to do |format|
      format.html { redirect_to species_path(@fact.species), notice: "Fact was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def fact_params
    params.require(:fact).permit(:fact, :species_id)
  end
end

app/controllers/admin/interface_controller.rb
class Admin::InterfaceController < SecuredController
  def index
    @species = Species.all
  end
end

app/controllers/admin/species_controller.rb
class Admin::SpeciesController < SecuredController
  def show
    @species = Species.find(params[:id])
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  around_action :switch_locale

  def switch_locale(&)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/api/facts_controller.rb
class Api::FactsController < Api::ApiController
  def index
    @fact = Fact.all.sample
    @photo = @fact.photos.sample
    @with_image = params[:image] == "true"
    @with_species_info = params[:species_info] == "true"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # maybe auth stuff
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # OmniAuth stores the information returned from Auth0 and the IdP in request.env['omniauth.auth'].
    # In this code, you will pull the raw_info supplied from the id_token and assign it to the session.
    # Refer to https://github.com/auth0/omniauth-auth0/blob/master/EXAMPLES.md#example-of-the-resulting-authentication-hash for complete information on 'omniauth.auth' contents.
    auth_info = request.env["omniauth.auth"]
    session[:userinfo] = auth_info["extra"]["raw_info"]

    # Redirect to the URL you want after successful auth
    redirect_to admin_interface_url
  end

  def failure
    # Handles failed authentication -- Show a failure page (you can also handle with a redirect)
    @error_msg = request.params["message"]
  end

  def logout
    reset_session
    redirect_to root_url, allow_other_host: true
  end

  private

  def logout_url
    request_params = {
      returnTo: root_url,
      client_id: AUTH0_CONFIG["auth0_client_id"]
    }

    URI::HTTPS.build(host: AUTH0_CONFIG["auth0_domain"], path: "/v2/logout", query: request_params.to_query).to_s
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  User = Data.define(
    :name,
    :email,
    :picture
  )

  included do
    before_action :logged_in_using_omniauth?
    before_action :set_current_user
  end

  def logged_in_using_omniauth?
    return if Rails.env.development?

    redirect_to "/" unless session[:userinfo].present?
  end

  def set_current_user
    return set_mock_user if Rails.env.development?

    @current_user = User.new(
      session[:userinfo]["nickname"],
      session[:userinfo]["name"],
      session[:userinfo]["picture"]
    )
  end

  def set_mock_user
    @current_user = User.new("testuser", "test", nil)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :redirect_if_logged_in
  before_action :redirect_if_development

  def index
  end

  private

  def redirect_if_logged_in
    redirect_to admin_interface_url if session[:userinfo].present?
  end

  def redirect_if_development
    redirect_to admin_interface_url if Rails.env.development?
  end
end

app/controllers/secured_controller.rb
class SecuredController < ApplicationController
  include Secured
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/admin/facts/_fact.html.erb
<%= turbo_frame_tag fact, class: "px-2 pt-2" do %>
  <div class="block max-w-sm h-48 p-4 bg-white border border-gray-200 rounded-lg shadow">
    <div class="h-4/6">
      <p class="line-clamp-3 font-normal text-gray-700"><%= fact.fact %></p>
    </div>
    <div class="flex justify-end mt-4">
      <%= button_to "🗡️ Delete", fact_path(fact), method: :delete, class: "font-bold rounded duration-150 bg-red-500 text-white hover:bg-red-700 py-2 pl-2 pr-4 mr-4", data: { turbo_method: :delete, turbo_confirm: "Confirm deletion of fact #{fact.id}" } %>
      <%= link_to "📝 Edit", edit_fact_path(fact), class: "font-bold rounded duration-150 bg-green-500 text-white hover:bg-green-700 py-2 pl-2 pr-4" %>
    </div>
  </div>
<% end %>

app/views/admin/facts/_form.html.erb
<%= form_with model: fact, class: "h-full" do |form| %>
  <div class="h-4/6">
    <%= form.text_area :fact, class: "form-input leading-tight w-full h-full" %>
    <%= form.hidden_field :species_id, value: fact.species_id %>
  </div>
  <div class="flex justify-end mt-4">
    <%= link_to "✖️ Cancel", species_path(fact.species), class: "font-bold rounded duration-150 bg-red-500 text-white hover:bg-red-700 py-2 pl-2 pr-4 mr-4" %>
    <%= form.submit "💾 Save", class: "cursor-pointer font-bold rounded duration-150 bg-green-500 text-white hover:bg-green-700 py-2 pl-2 pr-4" %>
  </div>
<% end %>

app/views/admin/facts/create.turbo_stream.erb
<%= turbo_stream.after "new_fact", partial: "admin/facts/fact", locals: { fact: @fact } %>
<%= turbo_stream.update "new_fact", partial: "admin/species/new_fact", locals: { species: @fact.species } %>

app/views/admin/facts/destroy.turbo_stream.erb
<%= turbo_stream.remove @fact %>

app/views/admin/facts/edit.html.erb
<div class="px-2 pt-2">
  <%= turbo_frame_tag @fact do %>
    <div class="block max-w-sm h-48 p-4 bg-white border border-gray-200 rounded-lg shadow">
      <%= render "form", fact: @fact %>
    </div>
  <% end %>
</div>

app/views/admin/facts/new.html.erb
<div class="px-2 pt-2">
  <%= turbo_frame_tag @fact do %>
    <div class="block max-w-sm h-48 p-4 bg-white border border-gray-200 rounded-lg shadow">
      <%= render "form", fact: @fact %>
    </div>
  <% end %>
</div>

app/views/admin/facts/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Facts#show</h1>
  <p>Find me in app/views/facts/show.html.erb</p>
</div>

app/views/admin/interface/index.html.erb
<div class="flex flex-col h-screen">
  <header class="bg-green-500 text-white py-4 flex flex-row justify-between items-stretch px-5">
    <div class="flex flex-row justify-start">
      <%= link_to admin_interface_url do%>
        <%= image_tag "logo.png", class: "w-10 h-10"%>
      <% end %>
      <h1 class="text-left text-2xl px-2 pt-2">Gaerdesmutte</h1>
    </div>
    <div class="flex flex-row justify-end">
      <% if @current_user.present? %>
        <span class="text-right pt-2"><%= @current_user.email %></span>
        <%= link_to "Logout", auth_logout_path, method: :get, class: "ml-4 pt-2" %>
      <% else %>
        <%= button_to 'Login', '/auth/auth0', method: :post, data: { turbo: false } %>
      <% end %>
    </div>
  </header>

  <div class="flex flex-1">
    <div class="w-1/6 bg-gray-50">
      <%= render @species %>
    </div>
    <%= turbo_frame_tag "species_show_area", class: "w-5/6 bg-gray-200 p-4 flex flex-col justify-center items-center" do %>
      <span>Stuff goes here...</span>
    <% end %>
  </div>
</div>

app/views/admin/species/__image_slider_old.html.erb
<div id="default-carousel" class="relative w-full" data-carousel="slide">
    <!-- Carousel wrapper -->
    <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
            <%= image_tag "wren1.jpg", class: "absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" %>
        </div>
    </div>
    <!-- Slider indicators -->
    <div class="absolute z-30 flex space-x-3 -translate-x-1/2 bottom-5 left-1/2">
        <button type="button" class="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="0"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 4" data-carousel-slide-to="3"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 5" data-carousel-slide-to="4"></button>
    </div>
    <!-- Slider controls -->
    <button type="button" class="absolute top-0 left-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-4 h-4 text-white dark:text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
            </svg>
            <span class="sr-only">Previous</span>
        </span>
    </button>
    <button type="button" class="absolute top-0 right-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-4 h-4 text-white dark:text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <span class="sr-only">Next</span>
        </span>
    </button>
</div>

app/views/admin/species/_carousel.html.erb
<div class="h-full flex flex-row justify-center items-center pb-5" data-controller="carousel">
  <button data-action="click->carousel#previous" type="button" class="flex items-center justify-center cursor-pointer group focus:outline-none" data-carousel-prev>
    <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-green-500 group-hover:bg-green-700">
      <svg class="w-4 h-4 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
      </svg>
    </span>
  </button>
  <% photos.each_with_index do |photo, idx| %>
    <div data-carousel-target="image" class="w-fit h-full flex justify-center items-center <%= idx > 0 ? "hidden" : nil %>">
      <%= link_to url_for(photo.blob), class: "scale-75 px-12" do %>
        <%= image_tag photo.blob.variant(resize_to_limit: [500, 500]), size: 500 %>
      <% end %>
    </div>
  <% end %>
  <button data-action="click->carousel#next" type="button" class="flex items-center justify-center cursor-pointer group focus:outline-none" data-carousel-next>
    <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-green-500 group-hover:bg-green-700">
      <svg class="w-4 h-4 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
      </svg>
    </span>
  </button>
</div>

app/views/admin/species/_new_fact.html.erb
<div class="block max-w-sm h-48 p-4 bg-white border border-gray-200 rounded-lg shadow">
  <div class="flex justify-center items-center h-full">
    <%= link_to "➕ New Fact", new_fact_path(params: {species_id: species.id}), class: "font-bold rounded duration-150 bg-green-500 text-white hover:bg-green-700 py-2 pl-2 pr-4" %>
  </div>
</div>

app/views/admin/species/_species.html.erb
<div class="px-2 pt-2" >
  <%= link_to species_url(species), data: { turbo_frame: "species_show_area" }, class: "block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700" do %>
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= species.scientific_name %></h5>
    <p class="font-normal text-gray-700 dark:text-gray-400"><%= species.common_name_en %></p>
    <p class="font-normal text-gray-700 dark:text-gray-400"><%= species.common_name_da %></p>
    <p class="font-normal text-gray-700 dark:text-gray-400">Facts: <%= species.facts.count %></p>
  <% end %>
</div>

app/views/admin/species/show.html.erb
<%= turbo_frame_tag "species_show_area", class: "w-5/6 p-4" do %>
  <div class="w-full justify-start h-12">
    <%= link_to "⬅️ Back", admin_interface_path, class: "font-bold rounded duration-150 bg-green-500 text-white hover:bg-green-700 py-2 pl-2 pr-4 ml-2" %>
  </div>
  <div class="w-full h-full">
    <div class="grid grid-cols-1 md:grid-cols-4 h-4/6 w-full">
      <%= turbo_frame_tag "new_fact", class: "px-2 pt-2" do %>
        <%= render partial: "new_fact", locals: { species: @species } %>
      <% end %>

      <%= render @species.facts.ordered %>
    </div>

    <% if @species.photos.any? %>
      <div class="h-2/6 w-full">
        <%= render partial: "carousel", locals: { photos: @species.photos } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaerdesmutte</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/login/index.html.erb
<div class="w-full h-screen flex flex-col justify-center items-center">
  <%= image_tag "logo.png", class: "w-24 h-24 mb-5" %>
  <%= button_to "Login", "/auth/auth0", method: :post, data: { turbo: false }, class: "font-bold rounded duration-150 bg-green-500 text-white hover:bg-green-700 py-2 px-4" %>
</div>